"""
Pydantic models for structured acquisition plans.

This module defines the structure for machine-executable acquisition plans
that are generated by the AnalysisTeam and consumed by the acquisition router.
The schema remains backward-compatible with the legacy DownloadPlan shape.
"""

from typing import List, Literal, Optional

from pydantic import BaseModel, Field, model_validator


AcquisitionStrategy = Literal[
    "repository_download",
    "author_contact",
    "embedded_extraction",
    "hybrid",
]
TaskType = Literal["repository_download", "author_contact", "embedded_extraction"]


class PlanStep(BaseModel):
    """A single step in the download plan."""

    step: int = Field(description="Step number in sequence")
    action: Literal["navigate", "download", "login", "preprocess", "input"] = Field(
        description="Type of action to perform"
    )
    description: str = Field(description="Human-readable description of the step")

    # Optional parameters for different action types
    url: Optional[str] = Field(None, description="URL to navigate to or download from")
    target_files: Optional[List[str]] = Field(None, description="Expected file names to download")
    condition: Optional[str] = Field(None, description="Condition that must be met before proceeding")
    method: Optional[str] = Field(None, description="Specific method or approach to use")
    prompt: Optional[str] = Field(None, description="Prompt for requesting user input (for 'input' action)")


class ContactTarget(BaseModel):
    """Author/contact target for author-contact acquisition."""

    name: Optional[str] = Field(None, description="Contact person name")
    email: Optional[str] = Field(None, description="Contact email address")
    role: Optional[str] = Field(None, description="Role such as corresponding author")
    institution: Optional[str] = Field(None, description="Institution or affiliation")
    notes: Optional[str] = Field(None, description="Additional contact notes")


class EmbeddedTarget(BaseModel):
    """Embedded paper data target such as a table or figure."""

    target_type: Literal["table", "figure", "supplement", "page"] = Field(
        description="Kind of embedded data target"
    )
    label: str = Field(description="Human-readable identifier such as Table S2 or Figure 3B")
    page_hint: Optional[str] = Field(None, description="Page number or page range hint")
    description: Optional[str] = Field(None, description="What data should be extracted")
    extraction_hint: Optional[str] = Field(None, description="Preferred extraction method or evidence")


class AcquisitionTask(BaseModel):
    """A routed acquisition task for one execution strategy."""

    task_type: TaskType = Field(description="Execution strategy for this task")
    priority: int = Field(1, description="Lower numbers run first")
    title: Optional[str] = Field(None, description="Task title for UI/logging")
    success_criteria: Optional[str] = Field(
        None, description="What constitutes success for this task"
    )
    steps: List[PlanStep] = Field(
        default_factory=list,
        description="Browser-executable steps for repository download tasks",
    )
    contact_targets: List[ContactTarget] = Field(
        default_factory=list,
        description="Targets for author-contact tasks",
    )
    embedded_targets: List[EmbeddedTarget] = Field(
        default_factory=list,
        description="Targets for embedded extraction tasks",
    )
    desired_outputs: List[str] = Field(
        default_factory=list,
        description="Data outputs expected from this task",
    )
    blocking_gaps: List[str] = Field(
        default_factory=list,
        description="What remains missing if this task completes only partially",
    )
    notes: Optional[str] = Field(None, description="Additional task notes")


class DownloadPlan(BaseModel):
    """Complete acquisition plan for a research paper."""

    source_paper_title: str = Field(description="Title of the source research paper")
    data_accessibility: str = Field(description="Data accessibility level (Public/Private/Upon Request)")
    repository: Optional[str] = Field(None, description="Data repository name if applicable")
    steps: List[PlanStep] = Field(
        default_factory=list,
        description="Legacy root-level repository download steps",
    )

    # Additional metadata
    requires_authentication: bool = Field(False, description="Whether authentication is required")
    estimated_download_size: Optional[str] = Field(None, description="Estimated size of data to download")
    preprocessing_required: bool = Field(False, description="Whether preprocessing is needed after download")
    notes: Optional[str] = Field(None, description="Additional notes or considerations")
    primary_strategy: AcquisitionStrategy = Field(
        "repository_download",
        description="Primary acquisition strategy for this paper",
    )
    tasks: List[AcquisitionTask] = Field(
        default_factory=list,
        description="Ordered acquisition tasks for routed execution",
    )
    desired_outputs: List[str] = Field(
        default_factory=list,
        description="Outputs expected across all tasks",
    )
    blocking_gaps: List[str] = Field(
        default_factory=list,
        description="Still-missing data after planned acquisition",
    )

    @model_validator(mode="before")
    @classmethod
    def _backfill_legacy_shape(cls, data):
        if not isinstance(data, dict):
            return data

        raw_steps = list(data.get("steps") or [])
        tasks = list(data.get("tasks") or [])
        primary_strategy = data.get("primary_strategy")

        if not tasks:
            inferred_task_type: TaskType
            if raw_steps:
                inferred_task_type = "repository_download"
            else:
                notes = (data.get("notes") or "").lower()
                accessibility = (data.get("data_accessibility") or "").lower()
                repository = (data.get("repository") or "").lower()
                if any(token in notes for token in ("contact author", "email author", "upon request")):
                    inferred_task_type = "author_contact"
                elif any(
                    token in notes
                    for token in ("embedded", "table", "figure", "supplementary", "supplement")
                ):
                    inferred_task_type = "embedded_extraction"
                elif "request" in accessibility and not repository:
                    inferred_task_type = "author_contact"
                else:
                    inferred_task_type = "repository_download"

            data["tasks"] = [
                {
                    "task_type": inferred_task_type,
                    "priority": 1,
                    "title": "Primary acquisition task",
                    "success_criteria": "Acquire the most relevant usable data for this paper",
                    "steps": raw_steps if inferred_task_type == "repository_download" else [],
                    "notes": data.get("notes"),
                    "desired_outputs": data.get("desired_outputs") or [],
                    "blocking_gaps": data.get("blocking_gaps") or [],
                }
            ]

        return data

    @model_validator(mode="after")
    def _sync_root_steps_and_strategy(self):
        if not self.tasks:
            self.tasks = [
                AcquisitionTask(
                    task_type="repository_download",
                    priority=1,
                    title="Primary acquisition task",
                    success_criteria="Acquire the most relevant usable data for this paper",
                    steps=list(self.steps),
                    notes=self.notes,
                    desired_outputs=list(self.desired_outputs),
                    blocking_gaps=list(self.blocking_gaps),
                )
            ]

        repo_task = next((task for task in self.tasks if task.task_type == "repository_download"), None)
        if repo_task and not self.steps:
            self.steps = list(repo_task.steps)

        task_types = {task.task_type for task in self.tasks}
        if len(task_types) > 1:
            self.primary_strategy = "hybrid"
        elif task_types:
            self.primary_strategy = next(iter(task_types))
        else:
            self.primary_strategy = "repository_download"

        return self

    def get_tasks_by_type(self, task_type: TaskType) -> List[AcquisitionTask]:
        return sorted(
            [task for task in self.tasks if task.task_type == task_type],
            key=lambda task: (task.priority, task.title or ""),
        )


AcquisitionPlan = DownloadPlan
