-- PostgreSQL schema for pipeline metadata (single source of truth for new installs).

CREATE TABLE IF NOT EXISTS projects (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    research_query TEXT NOT NULL,
    user_email TEXT NOT NULL DEFAULT 'doctor@ai4med.edu',
    max_papers INTEGER DEFAULT 10,
    status TEXT DEFAULT 'running',
    overall_progress DOUBLE PRECISION DEFAULT 0.0,
    parallel_pipeline BOOLEAN DEFAULT FALSE,
    analysis_model TEXT DEFAULT NULL,
    download_model TEXT DEFAULT NULL,
    date_start TEXT DEFAULT NULL,
    date_end TEXT DEFAULT NULL,
    search_backend TEXT DEFAULT 'pubmed',
    force_reanalyze BOOLEAN DEFAULT FALSE,
    -- MeSH expansion config + observability.
    mesh_expansion BOOLEAN DEFAULT TRUE,
    mesh_expanded_query TEXT DEFAULT NULL,
    mesh_expansion_status TEXT DEFAULT 'disabled',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS stages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id TEXT NOT NULL,
    stage_name TEXT NOT NULL,
    status TEXT DEFAULT 'pending',
    progress DOUBLE PRECISION DEFAULT 0.0,
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    duration_seconds INTEGER,
    error_message TEXT,
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS messages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id TEXT NOT NULL,
    stage_name TEXT,
    team_name TEXT,
    message_type TEXT DEFAULT 'info',
    content TEXT NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS artifacts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id TEXT NOT NULL,
    artifact_type TEXT NOT NULL,
    file_path TEXT NOT NULL,
    file_name TEXT,
    file_content TEXT,
    -- BIGINT because dataset payloads frequently exceed 2 GB (single-cell
    -- .cloupe.gz, GEO matrix dumps, etc.). INTEGER overflows silently
    -- abort the INSERT, leaving the storage backend with an orphan blob.
    file_size BIGINT,
    stage_name TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    data_classification_flag TEXT,
    storage_backend TEXT DEFAULT 'local',
    s3_bucket TEXT,
    s3_key TEXT,
    oss_bucket TEXT,
    oss_key TEXT,
    acquisition_source TEXT,
    acquisition_status TEXT,
    trust_level TEXT,
    confidence DOUBLE PRECISION,
    produced_by TEXT,
    provenance JSONB DEFAULT '{}'::jsonb,
    email_sent_at TIMESTAMP,
    -- Review Queue state machine.
    -- Allowed values: pending / processing / handled / skipped
    human_review_status TEXT DEFAULT 'pending',
    -- Qualify-stage verdict for dataset artifacts.
    -- Allowed values: pending / processing / strict / loose / fail / error
    qualification_status TEXT DEFAULT 'pending',
    -- Decisive reason for the qualify verdict (shown inline with the verdict).
    qualification_reason TEXT,
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

-- Per-paper, per-stage LLM cost telemetry (analyze / download / qualify).
-- Single source of truth for tokens / cost / duration so per-paper total cost
-- is SUM(cost_usd) GROUP BY paper_name. paper_name is the shared basename across
-- stages (papers/<X>.pdf → analyses/<X>.md → datasets/<X>/).
CREATE TABLE IF NOT EXISTS stage_costs (
    id SERIAL PRIMARY KEY,
    project_id TEXT NOT NULL,
    paper_name TEXT NOT NULL,
    stage TEXT NOT NULL,
    model TEXT,
    input_tokens BIGINT DEFAULT 0,
    output_tokens BIGINT DEFAULT 0,
    cost_usd DOUBLE PRECISION DEFAULT 0,
    duration_ms BIGINT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE (project_id, paper_name, stage),
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_stage_costs_project ON stage_costs(project_id);

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    hashed_password TEXT NOT NULL,
    role TEXT DEFAULT 'user',
    is_active INTEGER DEFAULT 1,
    password_reset_token TEXT,
    password_reset_expires TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS linked_accounts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email TEXT NOT NULL,
    site TEXT NOT NULL,
    credential TEXT NOT NULL,
    encrypted_password TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_email, site)
);

CREATE TABLE IF NOT EXISTS execution_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Nullable: system-level audit events (admin user-mgmt, lifespan
    -- reconciliation, etc.) don't belong to a project.
    project_id TEXT,
    stage_name TEXT,
    team_name TEXT,
    event_type TEXT NOT NULL,
    message TEXT NOT NULL,
    severity TEXT DEFAULT 'info',
    payload JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_projects_user_email ON projects(user_email);
CREATE INDEX IF NOT EXISTS idx_projects_status ON projects(status);
-- Functional index for the main project list sort: ORDER BY COALESCE(updated_at, created_at) DESC
CREATE INDEX IF NOT EXISTS idx_projects_sort_key ON projects(COALESCE(updated_at, created_at) DESC);
CREATE INDEX IF NOT EXISTS idx_stages_project ON stages(project_id);
-- Composite covers: WHERE project_id=? AND stage_name=? ORDER BY start_time DESC NULLS LAST
CREATE INDEX IF NOT EXISTS idx_stages_project_name_time
    ON stages(project_id, stage_name, start_time DESC NULLS LAST);
CREATE INDEX IF NOT EXISTS idx_messages_project ON messages(project_id);
CREATE INDEX IF NOT EXISTS idx_artifacts_project ON artifacts(project_id);
CREATE INDEX IF NOT EXISTS idx_artifacts_data_flag ON artifacts(data_classification_flag);
CREATE INDEX IF NOT EXISTS idx_artifacts_acquisition_status ON artifacts(acquisition_status);
CREATE INDEX IF NOT EXISTS idx_artifacts_acquisition_source ON artifacts(acquisition_source);
CREATE INDEX IF NOT EXISTS idx_artifacts_s3 ON artifacts(storage_backend, s3_key);
CREATE INDEX IF NOT EXISTS idx_artifacts_oss ON artifacts(storage_backend, oss_key);
-- idx_users_email omitted: the UNIQUE constraint on users.email already creates an implicit index
CREATE INDEX IF NOT EXISTS idx_linked_accounts_user ON linked_accounts(user_email);
CREATE INDEX IF NOT EXISTS idx_execution_logs_project ON execution_logs(project_id);
CREATE INDEX IF NOT EXISTS idx_execution_logs_project_stage ON execution_logs(project_id, stage_name);
CREATE INDEX IF NOT EXISTS idx_execution_logs_event_type ON execution_logs(event_type);

-- Composite indexes for timeline / list / artifact-type access patterns.
CREATE INDEX IF NOT EXISTS idx_messages_project_timestamp
    ON messages(project_id, timestamp DESC);
-- Covers stage-filtered message queries: WHERE project_id=? AND stage_name=?
CREATE INDEX IF NOT EXISTS idx_messages_project_stage
    ON messages(project_id, stage_name, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_execution_logs_project_created
    ON execution_logs(project_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_artifacts_project_type
    ON artifacts(project_id, artifact_type);
CREATE UNIQUE INDEX IF NOT EXISTS idx_artifacts_project_type_path
    ON artifacts(project_id, artifact_type, file_path);
-- Functional index for cross-project paper dedup via S2 paper_id stored in provenance JSONB.
-- Partial: only rows that actually carry an s2_paper_id are indexed.
-- Legacy S2 path; new PubMed projects do NOT write the s2_paper_id key (so this index
-- is read-only for historical projects after the S2 retirement).
CREATE INDEX IF NOT EXISTS idx_artifacts_provenance_s2id
    ON artifacts((provenance->>'s2_paper_id'))
    WHERE provenance->>'s2_paper_id' IS NOT NULL;

-- Parallel functional index for PubMed PMID dedup. Defensive `!= ''`
-- guard in addition to IS NOT NULL — empty strings shouldn't be written, but
-- belt-and-braces protects the index from latent code paths.
CREATE INDEX IF NOT EXISTS idx_artifacts_provenance_pmid
    ON artifacts((provenance->>'pmid'))
    WHERE provenance->>'pmid' IS NOT NULL AND provenance->>'pmid' != '';

-- Global papers metadata table (PMID-keyed).
-- The S2 exit strategy makes PMID the canonical paper identifier; legacy
-- S2-backed projects do NOT populate this table — they continue using
-- artifacts.provenance only. analysis_cache references papers via FK.
CREATE TABLE IF NOT EXISTS papers (
    pmid TEXT PRIMARY KEY,
    doi TEXT,
    pmcid TEXT,
    title TEXT,
    authors TEXT,            -- JSON-encoded list (string for simplicity)
    publication_date TEXT,   -- YYYY/MM/DD per pipeline convention
    journal TEXT,
    first_seen_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_papers_doi
    ON papers(doi) WHERE doi IS NOT NULL;

-- Review Queue index is created in connection.py:init_schema()
-- AFTER the ALTER TABLE adds human_review_status column. Putting it here
-- breaks rolling deploys against existing DBs whose artifacts table was
-- created before this column existed (the partial-index predicate
-- references a not-yet-existing column).

-- Global analysis cache (cross-user compute reuse).
-- Composite key (pmid, model_name, prompt_hash, content_hash) implements
-- B3 version-bound invalidation per brainstorm decision.
--
-- PRIVACY: no user_email / project_id columns. The cache content is
-- derived from the public paper; per-user visibility is tracked separately
-- via the artifacts table (which is project-scoped). Cross-user cache hits
-- never expose the original creator's identity.
CREATE TABLE IF NOT EXISTS analysis_cache (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pmid TEXT NOT NULL,
    model_name TEXT NOT NULL,
    prompt_hash TEXT NOT NULL,
    content_hash TEXT NOT NULL,
    analysis_markdown TEXT NOT NULL,
    plan_json JSONB,
    data_classification_flag TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (pmid) REFERENCES papers(pmid) ON DELETE CASCADE,
    UNIQUE (pmid, model_name, prompt_hash, content_hash)
);
-- The UNIQUE constraint above creates an implicit btree index covering
-- exactly the cache-lookup columns in correct order — adding an explicit
-- CREATE INDEX would be a redundant duplicate (connection.py:L246
-- removed an instance of this anti-pattern).

-- Pre-screen scores. Written at score time for EVERY scored
-- candidate (passed / filtered / error) so recall verification can audit why
-- each paper passed or failed. Keyed (project_id, paper_id): unlike `papers`
-- this carries the project dimension and works for both PMID and S2 ids, and
-- is written before download/dedup so filtered + not-downloaded papers are
-- captured too. ON CONFLICT upsert (DAO) makes re-runs safe.
CREATE TABLE IF NOT EXISTS prescreen_scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id TEXT,
    paper_id TEXT NOT NULL,
    prescreen_score DOUBLE PRECISION,   -- NULL = LLM failure (prescreen error)
    prescreen_model TEXT,
    threshold DOUBLE PRECISION,
    decision TEXT,                      -- passed / filtered / error
    scored_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (project_id, paper_id)
);

-- Cross-project pre-screen cache. Global asset (no project_id /
-- user_email) like analysis_cache — lets same-keyword projects reuse a paper's
-- title/abstract score instead of re-calling the LLM. No FK to papers because
-- prescreen runs before papers rows are upserted. content_hash invalidates on
-- title/abstract change; prompt_hash (PRESCREEN_PROMPT_TEMPLATE_VERSION) on
-- prompt change.
CREATE TABLE IF NOT EXISTS prescreen_cache (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paper_id TEXT NOT NULL,
    model_name TEXT NOT NULL,
    prompt_hash TEXT NOT NULL,
    content_hash TEXT NOT NULL,
    prescreen_score DOUBLE PRECISION NOT NULL,
    prescreen_reason TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (paper_id, model_name, prompt_hash, content_hash)
);
CREATE INDEX IF NOT EXISTS idx_prescreen_cache_lookup
    ON prescreen_cache (model_name, prompt_hash, paper_id);
